/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedBillsIndexRouteImport } from './routes/_authenticated/bills/index'
import { Route as AuthenticatedBillsBillIdRouteImport } from './routes/_authenticated/bills/$billId'
import { Route as AuthenticatedBuddiesIndexRouteImport } from './routes/_authenticated/buddies/index'
import { Route as AuthenticatedBuddiesBuddyIdRouteImport } from './routes/_authenticated/buddies/$buddyId'
import { Route as AuthenticatedGroupsIndexRouteImport } from './routes/_authenticated/groups/index'
import { Route as AuthenticatedGroupsGroupIdRouteImport } from './routes/_authenticated/groups/$groupId'
import { Route as AuthenticatedGroupsGroupIdMembersMemberIdRouteImport } from './routes/_authenticated/groups/$groupId.members.$memberId'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillsIndexRoute = AuthenticatedBillsIndexRouteImport.update({
  id: '/bills/',
  path: '/bills/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillsBillIdRoute =
  AuthenticatedBillsBillIdRouteImport.update({
    id: '/bills/$billId',
    path: '/bills/$billId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBuddiesIndexRoute =
  AuthenticatedBuddiesIndexRouteImport.update({
    id: '/buddies/',
    path: '/buddies/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBuddiesBuddyIdRoute =
  AuthenticatedBuddiesBuddyIdRouteImport.update({
    id: '/buddies/$buddyId',
    path: '/buddies/$buddyId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGroupsIndexRoute =
  AuthenticatedGroupsIndexRouteImport.update({
    id: '/groups/',
    path: '/groups/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGroupsGroupIdRoute =
  AuthenticatedGroupsGroupIdRouteImport.update({
    id: '/groups/$groupId',
    path: '/groups/$groupId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGroupsGroupIdMembersMemberIdRoute =
  AuthenticatedGroupsGroupIdMembersMemberIdRouteImport.update({
    id: '/members/$memberId',
    path: '/members/$memberId',
    getParentRoute: () => AuthenticatedGroupsGroupIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/bills/$billId': typeof AuthenticatedBillsBillIdRoute
  '/buddies/$buddyId': typeof AuthenticatedBuddiesBuddyIdRoute
  '/groups/$groupId': typeof AuthenticatedGroupsGroupIdRouteWithChildren
  '/bills/': typeof AuthenticatedBillsIndexRoute
  '/buddies/': typeof AuthenticatedBuddiesIndexRoute
  '/groups/': typeof AuthenticatedGroupsIndexRoute
  '/groups/$groupId/members/$memberId': typeof AuthenticatedGroupsGroupIdMembersMemberIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
  '/bills/$billId': typeof AuthenticatedBillsBillIdRoute
  '/buddies/$buddyId': typeof AuthenticatedBuddiesBuddyIdRoute
  '/groups/$groupId': typeof AuthenticatedGroupsGroupIdRouteWithChildren
  '/bills': typeof AuthenticatedBillsIndexRoute
  '/buddies': typeof AuthenticatedBuddiesIndexRoute
  '/groups': typeof AuthenticatedGroupsIndexRoute
  '/groups/$groupId/members/$memberId': typeof AuthenticatedGroupsGroupIdMembersMemberIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/bills/$billId': typeof AuthenticatedBillsBillIdRoute
  '/_authenticated/buddies/$buddyId': typeof AuthenticatedBuddiesBuddyIdRoute
  '/_authenticated/groups/$groupId': typeof AuthenticatedGroupsGroupIdRouteWithChildren
  '/_authenticated/bills/': typeof AuthenticatedBillsIndexRoute
  '/_authenticated/buddies/': typeof AuthenticatedBuddiesIndexRoute
  '/_authenticated/groups/': typeof AuthenticatedGroupsIndexRoute
  '/_authenticated/groups/$groupId/members/$memberId': typeof AuthenticatedGroupsGroupIdMembersMemberIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/settings'
    | '/bills/$billId'
    | '/buddies/$buddyId'
    | '/groups/$groupId'
    | '/bills/'
    | '/buddies/'
    | '/groups/'
    | '/groups/$groupId/members/$memberId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/settings'
    | '/'
    | '/bills/$billId'
    | '/buddies/$buddyId'
    | '/groups/$groupId'
    | '/bills'
    | '/buddies'
    | '/groups'
    | '/groups/$groupId/members/$memberId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/_authenticated/bills/$billId'
    | '/_authenticated/buddies/$buddyId'
    | '/_authenticated/groups/$groupId'
    | '/_authenticated/bills/'
    | '/_authenticated/buddies/'
    | '/_authenticated/groups/'
    | '/_authenticated/groups/$groupId/members/$memberId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bills/': {
      id: '/_authenticated/bills/'
      path: '/bills'
      fullPath: '/bills/'
      preLoaderRoute: typeof AuthenticatedBillsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bills/$billId': {
      id: '/_authenticated/bills/$billId'
      path: '/bills/$billId'
      fullPath: '/bills/$billId'
      preLoaderRoute: typeof AuthenticatedBillsBillIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/buddies/': {
      id: '/_authenticated/buddies/'
      path: '/buddies'
      fullPath: '/buddies/'
      preLoaderRoute: typeof AuthenticatedBuddiesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/buddies/$buddyId': {
      id: '/_authenticated/buddies/$buddyId'
      path: '/buddies/$buddyId'
      fullPath: '/buddies/$buddyId'
      preLoaderRoute: typeof AuthenticatedBuddiesBuddyIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/groups/': {
      id: '/_authenticated/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof AuthenticatedGroupsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/groups/$groupId': {
      id: '/_authenticated/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof AuthenticatedGroupsGroupIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/groups/$groupId/members/$memberId': {
      id: '/_authenticated/groups/$groupId/members/$memberId'
      path: '/members/$memberId'
      fullPath: '/groups/$groupId/members/$memberId'
      preLoaderRoute: typeof AuthenticatedGroupsGroupIdMembersMemberIdRouteImport
      parentRoute: typeof AuthenticatedGroupsGroupIdRoute
    }
  }
}

interface AuthenticatedGroupsGroupIdRouteChildren {
  AuthenticatedGroupsGroupIdMembersMemberIdRoute: typeof AuthenticatedGroupsGroupIdMembersMemberIdRoute
}

const AuthenticatedGroupsGroupIdRouteChildren: AuthenticatedGroupsGroupIdRouteChildren =
  {
    AuthenticatedGroupsGroupIdMembersMemberIdRoute:
      AuthenticatedGroupsGroupIdMembersMemberIdRoute,
  }

const AuthenticatedGroupsGroupIdRouteWithChildren =
  AuthenticatedGroupsGroupIdRoute._addFileChildren(
    AuthenticatedGroupsGroupIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedBillsBillIdRoute: typeof AuthenticatedBillsBillIdRoute
  AuthenticatedBuddiesBuddyIdRoute: typeof AuthenticatedBuddiesBuddyIdRoute
  AuthenticatedGroupsGroupIdRoute: typeof AuthenticatedGroupsGroupIdRouteWithChildren
  AuthenticatedBillsIndexRoute: typeof AuthenticatedBillsIndexRoute
  AuthenticatedBuddiesIndexRoute: typeof AuthenticatedBuddiesIndexRoute
  AuthenticatedGroupsIndexRoute: typeof AuthenticatedGroupsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedBillsBillIdRoute: AuthenticatedBillsBillIdRoute,
  AuthenticatedBuddiesBuddyIdRoute: AuthenticatedBuddiesBuddyIdRoute,
  AuthenticatedGroupsGroupIdRoute: AuthenticatedGroupsGroupIdRouteWithChildren,
  AuthenticatedBillsIndexRoute: AuthenticatedBillsIndexRoute,
  AuthenticatedBuddiesIndexRoute: AuthenticatedBuddiesIndexRoute,
  AuthenticatedGroupsIndexRoute: AuthenticatedGroupsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
