/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedBillsIndexRouteImport } from './routes/_authenticated/bills/index'
import { Route as AuthenticatedBillsBillIdRouteImport } from './routes/_authenticated/bills/$billId'
import { Route as AuthenticatedBuddiesIndexRouteImport } from './routes/_authenticated/buddies/index'
import { Route as AuthenticatedBuddiesBuddyIdRouteImport } from './routes/_authenticated/buddies/$buddyId'
import { Route as AuthenticatedTabsIndexRouteImport } from './routes/_authenticated/tabs/index'
import { Route as AuthenticatedTabsTabIdRouteImport } from './routes/_authenticated/tabs/$tabId'
import { Route as AuthenticatedTabsTabIdMembersMemberIdRouteImport } from './routes/_authenticated/tabs/$tabId.members.$memberId'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillsIndexRoute = AuthenticatedBillsIndexRouteImport.update({
  id: '/bills/',
  path: '/bills/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillsBillIdRoute =
  AuthenticatedBillsBillIdRouteImport.update({
    id: '/bills/$billId',
    path: '/bills/$billId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBuddiesIndexRoute =
  AuthenticatedBuddiesIndexRouteImport.update({
    id: '/buddies/',
    path: '/buddies/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBuddiesBuddyIdRoute =
  AuthenticatedBuddiesBuddyIdRouteImport.update({
    id: '/buddies/$buddyId',
    path: '/buddies/$buddyId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTabsIndexRoute = AuthenticatedTabsIndexRouteImport.update({
  id: '/tabs/',
  path: '/tabs/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTabsTabIdRoute = AuthenticatedTabsTabIdRouteImport.update({
  id: '/tabs/$tabId',
  path: '/tabs/$tabId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTabsTabIdMembersMemberIdRoute =
  AuthenticatedTabsTabIdMembersMemberIdRouteImport.update({
    id: '/members/$memberId',
    path: '/members/$memberId',
    getParentRoute: () => AuthenticatedTabsTabIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/welcome': typeof WelcomeRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/bills/$billId': typeof AuthenticatedBillsBillIdRoute
  '/buddies/$buddyId': typeof AuthenticatedBuddiesBuddyIdRoute
  '/tabs/$tabId': typeof AuthenticatedTabsTabIdRouteWithChildren
  '/bills/': typeof AuthenticatedBillsIndexRoute
  '/buddies/': typeof AuthenticatedBuddiesIndexRoute
  '/tabs/': typeof AuthenticatedTabsIndexRoute
  '/tabs/$tabId/members/$memberId': typeof AuthenticatedTabsTabIdMembersMemberIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/welcome': typeof WelcomeRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
  '/bills/$billId': typeof AuthenticatedBillsBillIdRoute
  '/buddies/$buddyId': typeof AuthenticatedBuddiesBuddyIdRoute
  '/tabs/$tabId': typeof AuthenticatedTabsTabIdRouteWithChildren
  '/bills': typeof AuthenticatedBillsIndexRoute
  '/buddies': typeof AuthenticatedBuddiesIndexRoute
  '/tabs': typeof AuthenticatedTabsIndexRoute
  '/tabs/$tabId/members/$memberId': typeof AuthenticatedTabsTabIdMembersMemberIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/welcome': typeof WelcomeRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/bills/$billId': typeof AuthenticatedBillsBillIdRoute
  '/_authenticated/buddies/$buddyId': typeof AuthenticatedBuddiesBuddyIdRoute
  '/_authenticated/tabs/$tabId': typeof AuthenticatedTabsTabIdRouteWithChildren
  '/_authenticated/bills/': typeof AuthenticatedBillsIndexRoute
  '/_authenticated/buddies/': typeof AuthenticatedBuddiesIndexRoute
  '/_authenticated/tabs/': typeof AuthenticatedTabsIndexRoute
  '/_authenticated/tabs/$tabId/members/$memberId': typeof AuthenticatedTabsTabIdMembersMemberIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/welcome'
    | '/settings'
    | '/bills/$billId'
    | '/buddies/$buddyId'
    | '/tabs/$tabId'
    | '/bills/'
    | '/buddies/'
    | '/tabs/'
    | '/tabs/$tabId/members/$memberId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/welcome'
    | '/settings'
    | '/'
    | '/bills/$billId'
    | '/buddies/$buddyId'
    | '/tabs/$tabId'
    | '/bills'
    | '/buddies'
    | '/tabs'
    | '/tabs/$tabId/members/$memberId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/welcome'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/_authenticated/bills/$billId'
    | '/_authenticated/buddies/$buddyId'
    | '/_authenticated/tabs/$tabId'
    | '/_authenticated/bills/'
    | '/_authenticated/buddies/'
    | '/_authenticated/tabs/'
    | '/_authenticated/tabs/$tabId/members/$memberId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  WelcomeRoute: typeof WelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bills/': {
      id: '/_authenticated/bills/'
      path: '/bills'
      fullPath: '/bills/'
      preLoaderRoute: typeof AuthenticatedBillsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bills/$billId': {
      id: '/_authenticated/bills/$billId'
      path: '/bills/$billId'
      fullPath: '/bills/$billId'
      preLoaderRoute: typeof AuthenticatedBillsBillIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/buddies/': {
      id: '/_authenticated/buddies/'
      path: '/buddies'
      fullPath: '/buddies/'
      preLoaderRoute: typeof AuthenticatedBuddiesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/buddies/$buddyId': {
      id: '/_authenticated/buddies/$buddyId'
      path: '/buddies/$buddyId'
      fullPath: '/buddies/$buddyId'
      preLoaderRoute: typeof AuthenticatedBuddiesBuddyIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tabs/': {
      id: '/_authenticated/tabs/'
      path: '/tabs'
      fullPath: '/tabs/'
      preLoaderRoute: typeof AuthenticatedTabsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tabs/$tabId': {
      id: '/_authenticated/tabs/$tabId'
      path: '/tabs/$tabId'
      fullPath: '/tabs/$tabId'
      preLoaderRoute: typeof AuthenticatedTabsTabIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tabs/$tabId/members/$memberId': {
      id: '/_authenticated/tabs/$tabId/members/$memberId'
      path: '/members/$memberId'
      fullPath: '/tabs/$tabId/members/$memberId'
      preLoaderRoute: typeof AuthenticatedTabsTabIdMembersMemberIdRouteImport
      parentRoute: typeof AuthenticatedTabsTabIdRoute
    }
  }
}

interface AuthenticatedTabsTabIdRouteChildren {
  AuthenticatedTabsTabIdMembersMemberIdRoute: typeof AuthenticatedTabsTabIdMembersMemberIdRoute
}

const AuthenticatedTabsTabIdRouteChildren: AuthenticatedTabsTabIdRouteChildren =
  {
    AuthenticatedTabsTabIdMembersMemberIdRoute:
      AuthenticatedTabsTabIdMembersMemberIdRoute,
  }

const AuthenticatedTabsTabIdRouteWithChildren =
  AuthenticatedTabsTabIdRoute._addFileChildren(
    AuthenticatedTabsTabIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedBillsBillIdRoute: typeof AuthenticatedBillsBillIdRoute
  AuthenticatedBuddiesBuddyIdRoute: typeof AuthenticatedBuddiesBuddyIdRoute
  AuthenticatedTabsTabIdRoute: typeof AuthenticatedTabsTabIdRouteWithChildren
  AuthenticatedBillsIndexRoute: typeof AuthenticatedBillsIndexRoute
  AuthenticatedBuddiesIndexRoute: typeof AuthenticatedBuddiesIndexRoute
  AuthenticatedTabsIndexRoute: typeof AuthenticatedTabsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedBillsBillIdRoute: AuthenticatedBillsBillIdRoute,
  AuthenticatedBuddiesBuddyIdRoute: AuthenticatedBuddiesBuddyIdRoute,
  AuthenticatedTabsTabIdRoute: AuthenticatedTabsTabIdRouteWithChildren,
  AuthenticatedBillsIndexRoute: AuthenticatedBillsIndexRoute,
  AuthenticatedBuddiesIndexRoute: AuthenticatedBuddiesIndexRoute,
  AuthenticatedTabsIndexRoute: AuthenticatedTabsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  WelcomeRoute: WelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
