/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedBillsIndexRouteImport } from './routes/_authenticated/bills/index'
import { Route as AuthenticatedBillsBillIdRouteImport } from './routes/_authenticated/bills/$billId'
import { Route as AuthenticatedBuddiesIndexRouteImport } from './routes/_authenticated/buddies/index'
import { Route as AuthenticatedGroupsIndexRouteImport } from './routes/_authenticated/groups/index'
import { Route as AuthenticatedGroupsGroupIdRouteImport } from './routes/_authenticated/groups/$groupId'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillsIndexRoute = AuthenticatedBillsIndexRouteImport.update({
  id: '/bills/',
  path: '/bills/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillsBillIdRoute =
  AuthenticatedBillsBillIdRouteImport.update({
    id: '/bills/$billId',
    path: '/bills/$billId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBuddiesIndexRoute =
  AuthenticatedBuddiesIndexRouteImport.update({
    id: '/buddies/',
    path: '/buddies/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGroupsIndexRoute =
  AuthenticatedGroupsIndexRouteImport.update({
    id: '/groups/',
    path: '/groups/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGroupsGroupIdRoute =
  AuthenticatedGroupsGroupIdRouteImport.update({
    id: '/groups/$groupId',
    path: '/groups/$groupId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/bills/$billId': typeof AuthenticatedBillsBillIdRoute
  '/groups/$groupId': typeof AuthenticatedGroupsGroupIdRoute
  '/bills/': typeof AuthenticatedBillsIndexRoute
  '/buddies/': typeof AuthenticatedBuddiesIndexRoute
  '/groups/': typeof AuthenticatedGroupsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/': typeof AuthenticatedIndexRoute
  '/bills/$billId': typeof AuthenticatedBillsBillIdRoute
  '/groups/$groupId': typeof AuthenticatedGroupsGroupIdRoute
  '/bills': typeof AuthenticatedBillsIndexRoute
  '/buddies': typeof AuthenticatedBuddiesIndexRoute
  '/groups': typeof AuthenticatedGroupsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/bills/$billId': typeof AuthenticatedBillsBillIdRoute
  '/_authenticated/groups/$groupId': typeof AuthenticatedGroupsGroupIdRoute
  '/_authenticated/bills/': typeof AuthenticatedBillsIndexRoute
  '/_authenticated/buddies/': typeof AuthenticatedBuddiesIndexRoute
  '/_authenticated/groups/': typeof AuthenticatedGroupsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/bills/$billId'
    | '/groups/$groupId'
    | '/bills/'
    | '/buddies/'
    | '/groups/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/'
    | '/bills/$billId'
    | '/groups/$groupId'
    | '/bills'
    | '/buddies'
    | '/groups'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/'
    | '/_authenticated/bills/$billId'
    | '/_authenticated/groups/$groupId'
    | '/_authenticated/bills/'
    | '/_authenticated/buddies/'
    | '/_authenticated/groups/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bills/': {
      id: '/_authenticated/bills/'
      path: '/bills'
      fullPath: '/bills/'
      preLoaderRoute: typeof AuthenticatedBillsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bills/$billId': {
      id: '/_authenticated/bills/$billId'
      path: '/bills/$billId'
      fullPath: '/bills/$billId'
      preLoaderRoute: typeof AuthenticatedBillsBillIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/buddies/': {
      id: '/_authenticated/buddies/'
      path: '/buddies'
      fullPath: '/buddies/'
      preLoaderRoute: typeof AuthenticatedBuddiesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/groups/': {
      id: '/_authenticated/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof AuthenticatedGroupsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/groups/$groupId': {
      id: '/_authenticated/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof AuthenticatedGroupsGroupIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedBillsBillIdRoute: typeof AuthenticatedBillsBillIdRoute
  AuthenticatedGroupsGroupIdRoute: typeof AuthenticatedGroupsGroupIdRoute
  AuthenticatedBillsIndexRoute: typeof AuthenticatedBillsIndexRoute
  AuthenticatedBuddiesIndexRoute: typeof AuthenticatedBuddiesIndexRoute
  AuthenticatedGroupsIndexRoute: typeof AuthenticatedGroupsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedBillsBillIdRoute: AuthenticatedBillsBillIdRoute,
  AuthenticatedGroupsGroupIdRoute: AuthenticatedGroupsGroupIdRoute,
  AuthenticatedBillsIndexRoute: AuthenticatedBillsIndexRoute,
  AuthenticatedBuddiesIndexRoute: AuthenticatedBuddiesIndexRoute,
  AuthenticatedGroupsIndexRoute: AuthenticatedGroupsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
